In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
df = pd.read_csv(r'C:\Users\mechz\Documents\Jobs_Analysis\job_postings.csv')
display(df)

columns = df.columns.tolist()
country_columns = [column for column in columns if 'job_country' in column]
via_columns = [column for column in columns if 'job_via' in column]
skill_columns = [column for column in columns if 'skill' in column]
schedule_columns = ['Contractor', 'Full-time', 'Internship', 'Part-time', 'Tempwork']
job_title_columns = [column for column in columns if 'job_title_short' in column]

print('Count for country columns')
for column in country_columns:
    print(df[column].sum())

print('Count for via columns')
for column in via_columns:
    print(df[column].sum())

print('Count for skill columns')
for column in skill_columns:
    print(df[column].sum())

print('Count for schedule columns')
for column in schedule_columns:
    print(df[column].sum())

print('Count for job title columns')
for column in job_title_columns:
    print(df[column].sum())

,job_work_from_home,job_no_degree_mention,job_health_insurance,salary_year_avg,job_posted_year,job_posted_month_sine,Contractor,Full-time,Internship,Part-time,...,job_country_France,job_country_Germany,job_country_India,job_country_Poland,job_country_South Africa,job_country_Spain,job_country_Sudan,job_country_United Kingdom,job_country_United States,job_country_other
0,0.0,0.0,1.0,120000.0,2024.0,0.500000,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,112500.0,2024.0,0.500000,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,111175.0,2023.0,0.866025,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,112500.0,2023.0,-0.500000,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,325000.0,2023.0,0.500000,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38355,0.0,0.0,1.0,90000.0,2023.0,1.000000,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
38356,0.0,0.0,0.0,129480.0,2023.0,0.866025,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
38357,0.0,0.0,0.0,300000.0,2023.0,-0.866025,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
38358,0.0,0.0,1.0,114500.0,2023.0,0.500000,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
38359,0.0,0.0,1.0,179000.0,2023.0,-0.500000,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

Count for country columns
771.0
244.0
301.0
907.0
251.0
148.0
165.0
2462.0
382.0
28929.0
3800.0
Count for via columns
5880.0
2592.0
1144.0
949.0
1350.0
5523.0
4052.0
6354.0
664.0
1850.0
8002.0
Count for skill columns
2707.0
9031.0
6648.0
3080.0
2149.0
8397.0
2068.0
2437.0
2328.0
2366.0
3983.0
5047.0
2965.0
2988.0
2479.0
24186.0
1951.0
5352.0
23627.0
2067.0
9572.0
2571.0
2756.0
3547.0
4405.0
7179.0
23828.0
2424.0
9078.0
2437.0
1865.0
Count for schedule columns
999.0
37338.0
161.0
1497.0
215.0
Count for job title columns
1294.0
109.0
10314.0
7837.0
9709.0
860.0
1860.0
2636.0
2716.0
1025.0

In [11]:
display(df[df['Full-time'] == 0])

,job_work_from_home,job_no_degree_mention,job_health_insurance,salary_year_avg,job_posted_year,job_posted_month_sine,Contractor,Full-time,Internship,Part-time,...,job_country_France,job_country_Germany,job_country_India,job_country_Poland,job_country_South Africa,job_country_Spain,job_country_Sudan,job_country_United Kingdom,job_country_United States,job_country_other
1,0.0,0.0,0.0,112500.0,2024.0,5.000000e-01,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,112500.0,2023.0,-5.000000e-01,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
62,0.0,0.0,0.0,75000.0,2024.0,5.000000e-01,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
65,1.0,0.0,0.0,137500.0,2023.0,1.224647e-16,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
68,0.0,0.0,0.0,75000.0,2024.0,5.000000e-01,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38234,0.0,1.0,0.0,100000.0,2023.0,1.000000e+00,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
38237,0.0,1.0,1.0,77500.0,2023.0,-5.000000e-01,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
38255,0.0,0.0,1.0,114070.0,2023.0,8.660254e-01,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
38330,0.0,0.0,0.0,44100.0,2023.0,1.000000e+00,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
38336,0.0,1.0,0.0,100000.0,2023.0,-2.449294e-16,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0